#!/usr/bin/env python3
"""Generate compose.devices.yml (one service per sensor and per actuator) from config/rooms.json.

    python3 scripts/gen_compose.py            # writes compose.devices.yml
    docker compose up --build                 # docker-compose.yml `include`s the generated file

Why generated: 5 rooms × (2 sensors + 2 actuators) = 20 device containers. Writing them by hand
guarantees drift between the config, the Compose file and the C4 container diagram.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CFG = json.loads((ROOT / "config" / "rooms.json").read_text(encoding="utf-8"))
OUT = ROOT / "compose.devices.yml"

SHORT = {"co2": "co2", "temperature": "temp"}


def svc_sensor(room: dict, s: dict) -> tuple[str, dict]:
    short = SHORT[s["type"]]
    name = f"sensor-{short}-{room['name'].lower()}"
    return name, {
        "image": "d7065e/sensor",
        "build": {"context": ".", "dockerfile": "sensor/Dockerfile"},
        "environment": {
            "SENSOR_ID": f"{room['name']}-{short}", "ROOM": room["name"], "LEVEL": CFG["level"],
            "TYPE": s["type"], "UNIT": s["unit"], "SAMPLE_S": s["sample_s"],
            "NOISE_SIGMA": s["noise_sigma"], "LAG_S": s["lag_s"],
            "PHYSICS_URL": "http://physics:8000", "BUILDSIM_URL": "${BUILDSIM_URL:-http://buildsim:9090}", "MQTT_HOST": "broker",
        },
        "depends_on": {"broker": {"condition": "service_healthy"}, "physics": {"condition": "service_healthy"}},
        "restart": "unless-stopped",
        "labels": {"d7065e.layer": "device", "d7065e.room": room["name"], "d7065e.type": s["type"]},
    }


def svc_actuator(room: dict, a: dict) -> tuple[str, dict]:
    name = f"actuator-{a['kind']}-{room['name'].lower()}"
    return name, {
        "image": "d7065e/actuator",
        "build": {"context": ".", "dockerfile": "actuator/Dockerfile"},
        "environment": {
            "ACTUATOR_ID": f"{room['name']}-{a['kind']}", "ROOM": room["name"], "LEVEL": CFG["level"],
            "KIND": a["kind"], "BUILDSIM_TYPE": a["buildsim_type"], "MIN": a["min"], "MAX": a["max"],
            "RATE_PER_S": a["rate_per_s"], "INITIAL": a["initial"],
            "BUILDSIM_URL": "${BUILDSIM_URL:-http://buildsim:9090}", "MQTT_HOST": "broker",
        },
        "depends_on": {"broker": {"condition": "service_healthy"}},
        "restart": "unless-stopped",
        "labels": {"d7065e.layer": "device", "d7065e.room": room["name"], "d7065e.type": a["kind"]},
    }


def main() -> None:
    services: dict[str, dict] = {}
    for room in CFG["rooms"]:
        for s in CFG["sensors"]:
            n, d = svc_sensor(room, s)
            services[n] = d
        for a in CFG["actuators"]:
            n, d = svc_actuator(room, a)
            services[n] = d
    lines = ["# GENERATED by scripts/gen_compose.py from config/rooms.json — do not edit by hand.",
             "# One container per physical device (design decision D-05, docs/decision-log.md).", "services:"]
    for name, d in services.items():
        lines.append(f"  {name}:")
        lines.append(f"    image: {d['image']}")
        lines.append(f"    build: {{context: ., dockerfile: {d['build']['dockerfile']}}}")
        lines.append("    environment:")
        for k, v in d["environment"].items():
            lines.append(f"      {k}: \"{v}\"")
        lines.append("    depends_on:")
        for k, v in d["depends_on"].items():
            lines.append(f"      {k}: {{condition: {v['condition']}}}")
        lines.append(f"    restart: {d['restart']}")
        lines.append("    labels: {" + ", ".join(f"{k}: {v}" for k, v in d["labels"].items()) + "}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(services)} device services")


if __name__ == "__main__":
    main()
